# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reactnotifi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Reactnotifi
  pod 'GoogleSignIn'
  target 'ReactnotifiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Reactnotifi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Reactnotifi-tvOS

end
